// Generated by CoffeeScript 1.6.2
(function() {
  var PointerLock;

  PointerLock = {
    lockAndFullscreen: function(el, callbackObj) {
      if (callbackObj == null) {
        callbackObj = {};
      }
      this.init(callbackObj);
      return this.fullScreenLock(el);
    },
    init: function(callbackObj) {
      var onDisable, onEnable, self;
      if (callbackObj == null) {
        callbackObj = {};
      }
      this.enabled = false;
      self = this;
      onEnable = callbackObj.onEnable, onDisable = callbackObj.onDisable;
      return ["", "moz", "webkit"].forEach(function(prefix) {
        var changeCallback;
        changeCallback = function(e) {
          self.enabled = !self.enabled;
          if (self.enabled) {
            if (typeof onEnable === "function") {
              onEnable();
            }
          } else {
            if (typeof onDisable === "function") {
              onDisable();
            }
          }
          return document.querySelector("#status").textContent = self.enabled ? "locked!" : "not locked";
        };
        return document.addEventListener(prefix + 'pointerlockchange', changeCallback, false);
      });
    },
    fullScreenLock: function(container) {
      var onFirefox, onScreenChange;
      console.log("enabling full lock....", this.enabled);
      if (this.enabled) {
        return;
      }
      console.log("not returned");
      container.fullScreenLock = container.fullScreenLock || container.mozRequestPointerLock || container.webkitRequestPointerLock;
      onFirefox = container.mozRequestFullScreen != null;
      if (onFirefox) {
        onScreenChange = function() {
          if (document.mozFullScreenElement === container) {
            return container.fullScreenLock();
          }
        };
        document.addEventListener("mozfullscreenchange", onScreenChange, false);
        return container.mozRequestFullScreen();
      } else {
        container.fullScreenLock();
        return container.webkitRequestFullScreen();
      }
    }
  };

  window.onload = function() {
    var button;
    button = document.querySelector("#click");
    return button.addEventListener("click", function() {
      return PointerLock.lockAndFullscreen(document.querySelector("body"), {
        onEnable: function() {
          return console.log("enabled!");
        },
        onDisable: function() {
          return console.log("disabled!");
        }
      });
    });
  };

}).call(this);
