// Generated by CoffeeScript 1.6.2
(function() {
  var changeCallback, prefix, requestPointerLock, _i, _len, _ref,
    __slice = [].slice;

  requestPointerLock = function(container) {
    var fullscreenChange;
    container.requestPointerLock = container.requestPointerLock || container.mozRequestPointerLock || container.webkitRequestPointerLock;
    if (container.mozRequestFullScreen) {
      container.mozRequestFullScreen();
      return document.addEventListener("mozfullscreenchange", (fullscreenChange = function() {
        if (document.mozFullScreenElement === container) {
          return container.requestPointerLock();
        }
      }), false);
    } else {
      return container.requestPointerLock();
    }
  };

  changeCallback = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    console.log("pointer lock changed");
    return console.log(args);
  };

  _ref = ["", "moz", "webkit"];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    prefix = _ref[_i];
    document.addEventListener(prefix + 'pointerlockchange', changeCallback, false);
  }

  window.onload = function() {
    var button;
    button = document.querySelector("#click");
    return button.addEventListener("click", function() {
      return requestPointerLock(button);
    });
  };

}).call(this);
