// Generated by CoffeeScript 1.6.2
(function() {
  var changeCallback, requestPointerLock,
    __slice = [].slice;

  requestPointerLock = function(container) {
    var fullscreenChange;
    container.requestPointerLock = container.requestPointerLock || container.mozRequestPointerLock || container.webkitRequestPointerLock;
    if (container.mozRequestFullScreen) {
      container.mozRequestFullScreen();
      return document.addEventListener("mozfullscreenchange", (fullscreenChange = function() {
        if (document.mozFullScreenElement === container) {
          return container.requestPointerLock();
        }
      }), false);
    } else {
      return container.requestPointerLock();
    }
  };

  changeCallback = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    console.log("pointer lock changed");
    return console.log(args);
  };

  document.addEventListener('pointerlockchange', changeCallback, false);

  document.addEventListener('mozpointerlockchange', changeCallback, false);

  document.addEventListener('webkitpointerlockchange', changeCallback, false);

}).call(this);
